version: '3'

volumes:
  pg_data:
  static:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./service/
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/backend_static
  gateway:
    build: ./nginx/
    env_file: .env
    ports:
      - 8000:80
    volumes:
      - static:/backend_static
    depends_on:
      - backend
  
