# Generated by Django 5.0 on 2023-12-23 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_order_discount_order_of_items_order_item_tax'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='item',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_of_items',
            name='order',
        ),
        migrations.RemoveField(
            model_name='order_of_items',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.DeleteModel(
            name='Discount',
        ),
        migrations.DeleteModel(
            name='Tax',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Order_of_items',
        ),
    ]
