# Generated by Django 5.0 on 2023-12-23 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_order_item_remove_tax_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Price', fields=[
                ('id', models.BigAutoField(
                    auto_created=True, primary_key=True, serialize=False, verbose_name='ID')), ('currency', models.CharField(
                        default='USD', max_length=3)), ('stripe_price_id', models.CharField(
                            max_length=100)), ('price', models.IntegerField(
                                default=0)), ('product', models.ForeignKey(
                                    on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='app.item')), ], ), ]
