# Generated by Django 5.0 on 2023-12-24 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_order_discount_order_of_items_order_item_tax'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
