# Generated by Django 5.0 on 2023-12-24 12:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_discount_order_alter_tax_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discount',
            name='order',
        ),
        migrations.RemoveField(
            model_name='tax',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='tax',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='orders',
                to='app.discount'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True),
        ),
        migrations.AlterField(
            model_name='tax',
            name='name',
            field=models.CharField(
                max_length=100,
                unique=True),
        ),
    ]
